import React,{useMemo,useState} from 'react';
import {ArrowLeft,Bookmark,Check,CheckCircle2,MapPin,Share2,ShieldCheck} from 'lucide-react';
import {useMarketplace} from '../context/MarketplaceContext';
import {ConditionBadge} from '../components/common/ConditionBadge';
import {UserAvatar} from '../components/common/UserAvatar';
import {Button} from '../components/common/Button';
import type {SellerListing} from '../types';
import {getPublicationCover} from '../lib/publicationEditions';

export const BookDetailsPage:React.FC=()=>{
 const {selectedBookId,books,setActiveView,createOrder,navigateToOrder,toggleWishlist,isWishlisted,user,openAuthModal,pickupPoints,setPrefillSellData}=useMarketplace();
 const book=books.find(b=>b.id===selectedBookId); const [offer,setOffer]=useState<SellerListing|null>(null); const [pickup,setPickup]=useState(pickupPoints[0]?.id||'pk-1'); const [copied,setCopied]=useState(false); const [busy,setBusy]=useState(false);
 const offers=useMemo(()=>(book?.offers??[]).filter(o=>o.availability==='Available').sort((a,b)=>a.sellingPrice-b.sellingPrice),[book]);
 if(!book)return <div className="p-10 bg-white rounded-3xl text-center"><p>Book model not found.</p><Button onClick={()=>setActiveView('browse')}>Back to browse</Button></div>;
 const choose=(o:SellerListing)=>{if(!user)return openAuthModal('login','Please log in to buy this seller listing.');setOffer(o);setPickup(o.pickupPointId||pickupPoints[0]?.id||'pk-1')};
 const startSelling=()=>{setPrefillSellData({id:book.id,title:book.title,subjectCode:book.subjectCode,department:book.department,semester:book.semester});setActiveView('sell');window.scrollTo({top:0,behavior:'smooth'})};
 const confirm=async()=>{if(!offer)return;setBusy(true);const r=await createOrder(offer.id,pickup);setBusy(false);if(r.error)return alert(r.error);setOffer(null);if(r.orderId)navigateToOrder(r.orderId)};
 const share=()=>{navigator.clipboard?.writeText(`${location.origin}/?book=${encodeURIComponent(book.id)}`);setCopied(true);setTimeout(()=>setCopied(false),1500)};
 return <div className="space-y-6"><div className="flex justify-between"><button onClick={()=>setActiveView('browse')} className="inline-flex gap-2 items-center text-sm font-semibold"><ArrowLeft className="w-4"/>Browse</button><div className="flex gap-2"><button onClick={()=>toggleWishlist(book.id)} className="p-2 rounded-full border bg-white"><Bookmark className={`w-4 ${isWishlisted(book.id)?'fill-[#ef4d23] text-[#ef4d23]':''}`}/></button><button onClick={share} className="p-2 rounded-full border bg-white">{copied?<Check className="w-4"/>:<Share2 className="w-4"/>}</button></div></div>
 <section className="grid lg:grid-cols-12 gap-6"><div className="lg:col-span-5 bg-white rounded-3xl border p-5"><img src={book.images[0]} alt={book.title} className="w-full aspect-[4/3] object-contain rounded-2xl bg-[#f5f2ee]"/><div className="mt-4 p-3 rounded-xl bg-emerald-50 text-xs text-emerald-800 flex gap-2"><ShieldCheck className="w-4 shrink-0"/>The cover follows the selected publication; the common model cover is used only as fallback.</div></div><div className="lg:col-span-7 bg-white rounded-3xl border p-6 space-y-5"><div className="flex gap-2 flex-wrap"><span className="bg-[#0b0f1a] text-white rounded-full px-3 py-1 text-xs font-mono">BTEB {book.subjectCode}</span><span className={`rounded-full px-3 py-1 text-xs font-bold border ${book.publication==='Technical Publication'?'bg-sky-50 text-sky-700 border-sky-200':'bg-orange-50 text-orange-700 border-orange-200'}`}>{book.publication || 'Haque Publication'}</span>{(book.curriculumEntries?.length?book.curriculumEntries:[{id:'legacy',bookId:book.id,regulation:book.regulation||'2022',technologyCode:'',department:book.department,semester:book.semester}]).map(entry=><span key={`${entry.technologyCode}-${entry.semester}`} className="bg-[#f5f2ee] rounded-full px-3 py-1 text-xs">{entry.department} • {entry.semester}</span>)}</div><div><h1 className="text-3xl font-bold">{book.title}</h1><p className="text-neutral-500">By {book.author}{book.edition?` • ${book.edition}`:''}</p></div><div className="grid grid-cols-3 gap-3"><div className="p-4 rounded-2xl bg-[#f5f2ee]"><span className="text-xs text-neutral-500">Starting price</span><p className="text-xl font-bold">{offers.length?`৳${offers[0].sellingPrice}`:'No offers'}</p></div><div className="p-4 rounded-2xl bg-[#f5f2ee]"><span className="text-xs text-neutral-500">Available stock</span><p className="text-xl font-bold">{offers.length}</p></div><div className="p-4 rounded-2xl bg-[#f5f2ee]"><span className="text-xs text-neutral-500">Sellers</span><p className="text-xl font-bold">{new Set(offers.map(item=>item.seller.id)).size}</p></div></div><p className="text-sm text-neutral-600">Choose the common book first, then compare each seller’s physical copy below.</p></div></section>
 <section className="space-y-3"><div><h2 className="text-xl font-bold">Available seller offers</h2><p className="text-sm text-neutral-500">Each card is one specific physical copy.</p></div>{offers.length===0?<div className="bg-white rounded-2xl border p-8 text-center space-y-3"><p className="font-semibold text-neutral-800">Unavailable • Stock 0</p><p className="text-sm text-neutral-500">No seller offer yet. Be the first student to list this book.</p><Button onClick={startSelling}>Sell this book</Button></div>:offers.map(o=><article key={o.id} className="bg-white rounded-2xl border p-5 grid md:grid-cols-[1fr_auto] gap-4"><div className="flex gap-3"><img src={getPublicationCover(book,o.publication)} alt={`${book.title} — ${o.publication}`} className="w-14 h-20 object-cover rounded-lg border bg-[#f5f2ee]"/><UserAvatar src={o.seller.avatar} name={o.seller.name} isVerified={o.seller.isVerified}/><div><div className="flex gap-2 items-center"><h3 className="font-bold">{o.seller.name}</h3>{o.seller.isVerified&&<CheckCircle2 className="w-4 text-emerald-600"/>}</div><p className="text-xs text-neutral-500">{o.seller.department} • ⭐ {o.seller.rating}</p><div className="mt-2 flex flex-wrap gap-2"><ConditionBadge condition={o.condition}/><span className={`inline-flex px-2.5 py-1 rounded-full text-[11px] font-bold border ${o.publication==='Technical Publication'?'bg-sky-50 text-sky-700 border-sky-200':'bg-orange-50 text-orange-700 border-orange-200'}`}>{o.publication}</span></div><p className="text-sm text-neutral-600 mt-2">{o.conditionDetails||'No additional condition notes.'}</p><p className="text-xs text-neutral-500 mt-2 flex gap-1"><MapPin className="w-3"/>{o.pickupPointName}</p></div></div><div className="md:text-right flex md:flex-col items-center md:items-end justify-between gap-3"><div><p className="text-2xl font-bold">৳{o.sellingPrice}</p>{o.originalPrice>o.sellingPrice&&<p className="text-xs text-neutral-400 line-through">৳{o.originalPrice}</p>}</div><Button onClick={()=>choose(o)} disabled={o.seller.id===user?.id}>{o.seller.id===user?.id?'Your listing':'Buy this copy'}</Button></div></article>)}</section>
 {offer&&<div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-3xl p-6 max-w-md w-full space-y-4"><h3 className="text-xl font-bold">Buy from {offer.seller.name}</h3><p className="text-sm">{book.title} • {offer.publication} • {offer.condition} • <b>৳{offer.sellingPrice}</b></p><select value={pickup} onChange={e=>setPickup(e.target.value)} className="w-full p-3 rounded-xl border">{pickupPoints.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><div className="flex gap-2 justify-end"><Button variant="outline" onClick={()=>setOffer(null)}>Cancel</Button><Button onClick={confirm} disabled={busy}>{busy?'Placing…':'Confirm specific listing'}</Button></div></div></div>}
 </div>
};
